config/routes.rb
# -*- encoding : utf-8 -*-
Sinners::Application.routes.draw do  
  root :to => 'home#index'
  mount BsAdmin::Engine => '/admin'
  
  match '/agenda(/:permalink)' => "home#agenda", as: :home_agenda
  match '/sobre' => "home#sobre", as: :home_sobre
  match '/fotos' => "home#fotos", as: :home_fotos
  match '/fotos/:permalink' => "home#fotos_detail", as: :home_fotos_detail  
  match '/contato' => "home#contato", as: :home_contato
  match '/aniversarios' => "home#aniversarios", as: :home_aniversarios
  get '/aniversarios/lista(/:permalink)' => "home#aniversarios_lista", as: :home_aniversarios_lista
  post  '/agenda/:permalink/lista' => "home#agenda_lista_post", as: :home_agenda_lista
  post  '/aniversarios/lista' => "home#aniversarios_lista_post", as: :home_aniversarios_lista_post
end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
require 'date'

class HomeController < ApplicationController
  def index
    load_events
  end

  def agenda
    load_events
    if params[:permalink]
      @active_event = event_by_permalink
    else
      @active_event = @events.first
    end
  end

  def sobre
    @photos = []
    (1..8).each do |i|
      image = BsAdmin::Settings.image(:sobre_page, "photo#{i}")
      @photos << image unless image.blank?
    end
  end

  def fotos
    @galleries = Gallery.order('date DESC').page(params[:page]).per(8)
  end

  def fotos_detail
    @gallery = Gallery.find_by_permalink(params[:permalink])
  end

  def aniversarios
  end

  def contato
  end

  def agenda_lista_post
    @event, @guests = event_by_permalink, []

    if params[:email].blank? || !is_a_valid_email(params[:email])
      return render :json => { error: 'invalid email' }
    end

    if @event.guests_list_open?
      params[:name].each do |name|
        unless name.blank?
          @guests << @event.guests.create({ email: params[:email], name: name })
        end
      end
    end
    # begin    
    ContactMailer.agenda_lista(@event, @guests).deliver
    # rescue
    # end

    render :json => ""
  end

  def is_a_valid_email(email)
    (email =~ /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i)
  end

  def aniversarios_lista
    load_events
    unless params[:permalink].blank?
      @event = event_by_permalink
      @birthday_list = @event.birthday_lists.new
    else
      @birthday_list = BirthdayList.new
    end
    @events_for_select = all_future_events.order('date').select{ |e| e.birthday_lists_open? }.map{ |e| [e.label_for_select, e.id] }
  end

  def aniversarios_lista_post
    unless params[:birthday_list][:date].blank?
      params[:birthday_list][:date] = Time.strptime(params[:birthday_list][:date], "%d/%m/%Y").in_time_zone('Brasilia')
    end

    birthday_list = BirthdayList.new(params[:birthday_list])
    date = birthday_list.date
    event_date = birthday_list.event.date

    if birthday_list.valid?
      if date >= event_date - 4.days and date <= event_date + 4.days
        if birthday_list.save
          # begin
            ContactMailer.aniversarios_lista(birthday_list.event, birthday_list).deliver
          # rescue
          # end
        end
        render :json => ""

      else
        render json: { errors: { message: "A data do aniversário deve ser 4 dias antes ou depois da festa." }}
      end
    else
      render json: { errors: { message: "Os campos Festa, Nome do Aniversariante e Data do Aniversário devem ser preenchidos." }}
    end
  end

  private

  def number_of_next_events
    BsAdmin::Settings.setting(:index_page, :next_events).to_i || 4
  end

  def event_by_permalink
    Event.find_by_permalink(params[:permalink])
  end

  def load_events
    @events = all_future_events.order('date').take number_of_next_events
    @events = @events.select{ |s| s.show }
  end

  def all_future_events
    yesterday = Time.zone.today - 12.hour
    Event.where("date >= ?", yesterday)
  end
end

app/views/home/_event-box.html.slim
a.event.fake-link cover-image="#{event.cover_image_url(:main)}" href="#{home_agenda_url(event.permalink)}" class="#{'active' if event.id == active_event_id}"
  .date
    span.day= event.date.day
    span.weekday= PT_BR_WEEKDAYS_SHORT[event.date.wday]
  .party
    p= event.party

app/views/home/_page-wrapper.html.slim
.center-wrapper: #title
=yield

app/views/home/_social-links.html.slim
#social-share-links
  #facebook.link-container
    iframe allowtransparency="true" frameborder="0" scrolling="no" src="#{@active_event.facebook_link}" style="border:none; overflow:hidden; height:21px;"
  #tweeter.link-container
    iframe allowtransparency="true" frameborder="0" scrolling="no" src="#{@active_event.twitter_link}" style="width:115px; height:21px;"
  #google-plus.link-container
    iframe allowtransparency="true" frameborder="0" scrolling="no" src="#{@active_event.google_plus_link}" title="+1"

app/views/home/agenda.html.slim
-title "Agenda"
-og_image @active_event.cover_image_url if @active_event != nil
-og_description @active_event.title_date if @active_event != nil
h1.seo Agenda
= render :layout => "page-wrapper" do
  .center-wrapper: #events
    -@events.reverse.each do |e|
      = render :partial => "event-box", :formats => [:html], locals: { event: e, active_event_id: @active_event.id }
  
  -if @active_event != nil
    #active-event
      #col1
        .title.title-mobile= @active_event.title
        img src="#{@active_event.cover_image_url(:main)}"        
        -if @active_event.guests_list_open?
          #lista-desconto-btn.btn.btn-black.fake-link.opacity-hover NOME NA LISTA
        -if @active_event.birthday_lists_open?
          a.btn.btn-purple.fake-link.opacity-hover href="#{home_aniversarios_lista_url(@active_event.permalink)}" LISTA ANIVERSÁRIO
      #col2
        .title.title-desktop= @active_event.title
        .sharing= render "social-links"
        .content== @active_event.description
      .clearfix

-if @active_event != nil
  .modal-lista-desconto.bg
  .modal-lista-desconto.modal
    .modal-dialog
      =form_tag "#{home_agenda_lista_url(@active_event.permalink)}" do
        .wrapper
          input.clear id="email" name="email" type="text" placeholder="e-mail"
          -(1..5).each do |i|
            input.clear id="name_" name="name[]" type="text" placeholder="nome (#{i})"      
      .modal-footer
        a#enviar-lista-desconto.btn.btn-purple.fake-link.opacity-hover ENVIAR
        a#cancelar-lista-desconto.btn.btn-black.fake-link.opacity-hover CANCELAR

app/views/home/aniversarios.html.slim
-title "Aniversários"
h1.seo Aniversários
= render :layout => "page-wrapper" do
  .center-wrapper
  .center-wrapper: .text== br_text setting(:aniversarios_page, :text)
  .center-wrapper: .contact 
      p== "Telefone: #{setting :aniversarios_page, :telefone}"
      p== "E-mail: #{setting :aniversarios_page, :email}"
  .center-wrapper: .text-icon
  .center-wrapper.center-wrapper-100: a.btn.btn-black.btn-w320.fake-link.opacity-hover href="#{home_aniversarios_lista_url}" ENVIAR LISTA DE ANIVERSÁRIO
  

app/views/home/aniversarios_lista.html.slim
-title "Aniversários"
h1.seo Aniversários
= render :layout => "page-wrapper" do
  .center-wrapper
  .center-wrapper
    =form_for @birthday_list, { url: "#{home_aniversarios_lista_post_url}" } do |f|
      p
        label Festa
        .select-wrapper
          =f.select :event_id, @events_for_select
      p
        label Nome do Aniversariante
        =f.text_field :name
      p
        label E-mail
        =f.text_field :email
      p
        label Data do Aniversário
        =f.text_field :date, class: "datepicker"
      -(1..15).each do |i|
        p
          label= "Convidado (#{i})"
          =f.text_field "guest#{i}"
  .center-wrapper.center-wrapper-100: #enviar-lista-aniversario.btn.btn-black.btn-w320.fake-link.opacity-hover ENVIAR LISTA
        

app/views/home/contato.html.slim
-title "Contato"
h1.seo Contato
= render :layout => "page-wrapper" do
  .center-wrapper: .text== setting :contato_page, :top
  .center-wrapper.center-wrapper-100: a.image.opacity-hover target="_blank" href="https://www.google.com/maps/place/R.+Gen.+Lima+e+Silva,+426+-+Centro+Hist%C3%B3rico,+RS,+90050-102,+Brazil/data=!4m2!3m1!1s0x951979005c956357:0x38bbdf568ba592e1?sa=X&ei=DDtvVKDUJvHfsATM_4K4AQ&ved=0CB4Q8gEwAA"
  .center-wrapper: .text== setting :contato_page, :bottom

app/views/home/fotos.html.slim
-title "Fotos"
h1.seo Fotos
= render :layout => "page-wrapper" do
  #galleries
    -@galleries.each do |g|
      .gallery
        a href="#{home_fotos_detail_url(g.permalink)}"
          .block.same-height
            .bg style="background-image: url('#{g.cover_image_url(:main)}')"
            .fg
              .title= g.party
          .description
            .title= "#{g.formatted_date} // #{g.edition}"
            .pics= "#{g.photos.count} fotos"
    .clearfix
    =paginate @galleries

app/views/home/fotos_detail.html.slim
-title @gallery.title_date
-og_image @gallery.cover_image_url
-og_description @gallery.title_date
h1.seo= @gallery.title_date
= render :layout => "page-wrapper" do
  .center-wrapper: .text= @gallery.title_date
  #images
    -@gallery.photos.each do |p|
      .fancybox fancybox-content="#{p.image_url}"
        .image-wrapper.fake-link.same-height: .border-wrapper
          .image style="background-image: url('#{p.image_url(:main)}')"
    .clearfix

app/views/home/index.html.slim
#flyer
.bottom
  .left
    .menu
      ul
        li: a href="#{home_sobre_url}" Sobre
        li: a href="#{home_agenda_url}" Agenda
        / li: a href="#{home_fotos_url}" Fotos
        li: a href="#{home_aniversarios_url}" Aniversários
        li: a href="#{home_contato_url}" Contato
    a href="#{root_url}": .logo
  .right
    -@events.reverse.each do |e|
      = render :partial => "event-box", :formats => [:html], locals: { event: e, active_event_id: nil }

-@events.each do |e|
  .preload-image style="background-image: url('#{e.cover_image_url(:main)}')"

app/views/home/sobre.html.slim
-title "Sobre"
h1.seo Sobre
= render :layout => "page-wrapper" do
  .center-wrapper: .text== br_text(setting(:sobre_page, :text))
  .center-wrapper: .text-icon
  #images: .wrapper    
    -@photos.each do |p|
      .fancybox.image-wrapper.fake-link.same-height fancybox-content="#{p}"
        .border-wrapper: .image style="background-image: url('#{p}')"
    .clearfix